---
- name: Create host file for each machines
  template: src=hosts.j2 dest=/etc/hosts

- name: Install common package to each node
  dnf: name={{ item }} state=present
  with_items:
      - "{{ common_dependencies }}"
