---
- hosts: all
  user: fedora
  sudo: yes
  roles:
      - { role: commons, tags: ['config'] }

- hosts: backend
  user: fedora
  sudo: yes
  roles:
      - { role: backend, tags: ['backend'] }

- hosts: database
  user: fedora
  sudo: yes
  roles:
      - { role: database, tags: ['database'] }

- hosts: web
  user: fedora
  sudo: yes
  roles:
      - { role: web, tags: ['web'] }
